@startuml
'https://plantuml.com/sequence-diagram

class User
abstract class Media
class Movie
class Series
class Season
class Episode
class Category
class StreamingService
class FileHandler
class FileHandler
class Menu

@enduml